name: Hello1

on:
  push:
    branches:
      - Ubuntu
  workflow_dispatch:

jobs:
  run-prechecks:

    runs-on: self-hosted

    environment: vm

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Hello Runner
        run: |
          echo "Hello from my self-hosted runner"
          hostname
          uname -a
          whoami

      - name: SSH Remote Test
        env:
          SSH_PASSWORD: ${{ secrets.VM }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh \
            -o StrictHostKeyChecking=no \
            root@172.17.0.3 \
            "hostname && uname -a"
