name: my-third-workflow

on:
  push:
    branches:
      - ubuntu
  workflow_dispatch:

jobs:
  job_check_remote:
    runs-on: self-hosted
    environment: vm
    env:
      SSH_PASSWORD: ${{ secrets.VM }}
      remote_ip: 172.17.0.2 

    steps:
      - run: |
          echo "The details of the runner machine"
          u1="uname -a"
          echo "$u1" 
      - run: |
 
          remote_cmd="uname -a"
          sshpass -p "$SSH_PASSWORD" ssh \
            -o StrictHostKeyChecking=no \
            user1@"$remote_ip" \
            "$remote_cmd"

      - run : |
          echo "Copying python script to target container..."
          sshpass -p "$SSH_PASSWORD" scp \
            -o StrictHostKeyChecking=no \
            health_checks2.py \
            user1@"$remote_ip":/home/user1/

      - run: |
          echo "Executing health_checks.py on target container..."
          sshpass -p "$SSH_PASSWORD" ssh \
            -o StrictHostKeyChecking=no \
            user1@"$remote_ip" \
            "python3 /home/user1/health_checks2.py > /home/user1/report.txt 2>&1"

          echo "===== HEALTH REPORT ====="
          sshpass -p "$SSH_PASSWORD" ssh \
            -o StrictHostKeyChecking=no \
            user1@"$remote_ip" \
            "cat /home/user1//report.txt"
            
